#!/bin/sh
#  First approx of running xylan as daemon
#
#SNAME="-sname xylan-$$"

if [ ! -f xylan.config ]; then
    echo "need a config file named xylan.config"
    echo 1
fi

case $1 in
    "console")
	erl -config xylan.config -s xylan $SNAME
	;;
    "daemon"|"")
	erl -noinput -config xylan.config -s xylan $SNAME 2>&1 > /dev/null &
	echo "started xylan node: $SNAME"
	;;
esac


    



